#!/bin/bash

URL="https://github.com/dEnchanter/Team-Newton"
git clone $URL

folder=${URL:30}
new_folder=~/$folder
cd "${new_folder}"

for file in $(ls);
do
	if [[ $file == *.py ]];
	then
		python3 $file >> ../newton.csv
	elif [[ $file == *.r ]];
	then
		Rscript $file >> ../newton.csv
	elif [[ $file == *.rb ]];
	then
		ruby $file >> ../newton.csv
	elif [[ $file == *.js ]];
	then
		node $file >> ../newton.csv
	elif [[ $file == *.sh ]];
	then
		bash $file >> ../newton.csv
	fi
done
